name: ubuntu20.04 v9.0.0 build x86-64
run-name: CyberRT v9.0.0 build runner on ubuntu20 x86-64🚀

on:
  push:
    branches:
      - v9.0.0

jobs:
  build-amd-ubuntu20:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:20.04
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y lsb-release git wget pkg-config g++ cmake libpoco-dev uuid-dev libncurses5-dev python3-dev
          cd /workspace/${{ github.repository }} && ./scripts/install.sh
      - name: Build
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binaries
          path: /workspace/${{ github.repository }}/build

